backend:
  name: git-gateway
  branch: main # or master

media_folder: "images/uploads"
public_folder: "/images/uploads"

# Left empty or removed since you manage HTML files directly in your repository
collections: []
